[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'Townk/vim-autoclose'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'Yggdroot/indentLine'
[[plugins]]
repo = "davidhalter/jedi-vim"
on_ft = ['python']

[[plugins]]
repo = 'reireias/vim-cheatsheet' 

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
  source ~/.config/nvim/plugins/denite.vim
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
  source ~/.config/nvim/plugins/gitgutter.vim  
'''

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
  source ~/.config/nvim/plugins/fugitive.vim  
'''

[[plugins]]
repo = 'osyo-manga/vim-anzu'
hook_add = '''
  source ~/.config/nvim/plugins/anzu.vim  
'''


